
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.multi  
    ports:
      - "5001:5001"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
